version: '2'

services:
  web-gophar:
    container_name: kctf-jr-web-gophar
    build:
      context: ./
      dockerfile: Dockerfile
    image: kctf-jr/web-gopher:latest
    ports:
      - "10201:80"
    volumes:
      - ./src:/var/www/html